# Generated by Django 2.0.1 on 2018-02-19 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginaWeb', '0002_auto_20180219_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='id_asoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paginaWeb.Organizacion'),
        ),
    ]
