# Generated by Django 2.0.1 on 2018-02-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaWeb', '0003_auto_20180220_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='edad',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
