# Generated by Django 2.0.1 on 2018-02-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaWeb', '0005_auto_20180220_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacion',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='lng',
        ),
    ]
